# Generated by Django 4.2.5 on 2023-10-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_account_email_alter_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
