# Generated by Django 4.2.5 on 2023-10-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='minute',
            field=models.CharField(default='', max_length=20),
        ),
    ]
