# Generated by Django 4.2.5 on 2023-10-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reservation_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='minute',
            field=models.CharField(max_length=20),
        ),
    ]
