# Generated by Django 4.2.5 on 2023-10-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_account_phone_alter_reservation_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
